// mainTest1.js
// ........................................................
const Logica = require("../Logica.js");
var assert = require("assert");
// ........................................................
// main ()
// ........................................................
describe("Test 2: cambiar datos usuario", function () {
  // ....................................................
  // ....................................................
  var laLogica = null;
  // ....................................................
  // ....................................................
  it("conectar a la base de datos", function (hecho) {
    laLogica = new Logica("../db/tinder.db", function (err) {
      if (err) {
        throw new Error("No he podido conectar con tinder.db");
      }
      hecho();
    }); // it
  });

  // ....................................................
  // ....................................................

  it("puedo modificar los datos de un usuario", async function () {
    const user = {
      id: 1,
      username: "user_3489",
      age: 27,
      photo:
        "/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAAqACAAQAAAABAAAA4aADAAQAAAABAAAA4QAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/+IH2ElDQ19QUk9GSUxFAAEBAAAHyGFwcGwCIAAAbW50clJHQiBYWVogB9kAAgAZAAsAGgALYWNzcEFQUEwAAAAAYXBwbAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAABvZHNjbQAAAXgAAAWKY3BydAAABwQAAAA4d3RwdAAABzwAAAAUclhZWgAAB1AAAAAUZ1hZWgAAB2QAAAAUYlhZWgAAB3gAAAAUclRSQwAAB4wAAAAOY2hhZAAAB5wAAAAsYlRSQwAAB4wAAAAOZ1RSQwAAB4wAAAAOZGVzYwAAAAAAAAAUR2VuZXJpYyBSR0IgUHJvZmlsZQAAAAAAAAAAAAAAFEdlbmVyaWMgUkdCIFByb2ZpbGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1sdWMAAAAAAAAAHwAAAAxza1NLAAAAKAAAAYRkYURLAAAAJAAAAaxjYUVTAAAAJAAAAdB2aVZOAAAAJAAAAfRwdEJSAAAAJgAAAhh1a1VBAAAAKgAAAj5mckZVAAAAKAAAAmhodUhVAAAAKAAAApB6aFRXAAAAEgAAArhrb0tSAAAAFgAAAspuYk5PAAAAJgAAAuBjc0NaAAAAIgAAAwZoZUlMAAAAHgAAAyhyb1JPAAAAJAAAA0ZkZURFAAAALAAAA2ppdElUAAAAKAAAA5ZzdlNFAAAAJgAAAuB6aENOAAAAEgAAA75qYUpQAAAAGgAAA9BlbEdSAAAAIgAAA+pwdFBPAAAAJgAABAxubE5MAAAAKAAABDJlc0VTAAAAJgAABAx0aFRIAAAAJAAABFp0clRSAAAAIgAABH5maUZJAAAAKAAABKBockhSAAAAKAAABMhwbFBMAAAALAAABPBydVJVAAAAIgAABRxlblVTAAAAJgAABT5hckVHAAAAJgAABWQAVgFhAGUAbwBiAGUAYwBuAP0AIABSAEcAQgAgAHAAcgBvAGYAaQBsAEcAZQBuAGUAcgBlAGwAIABSAEcAQgAtAHAAcgBvAGYAaQBsAFAAZQByAGYAaQBsACAAUgBHAEIAIABnAGUAbgDoAHIAaQBjAEMepQB1ACAAaADsAG4AaAAgAFIARwBCACAAQwBoAHUAbgBnAFAAZQByAGYAaQBsACAAUgBHAEIAIABHAGUAbgDpAHIAaQBjAG8EFwQwBDMEMAQ7BEwEPQQ4BDkAIAQ/BEAEPgREBDAEOQQ7ACAAUgBHAEIAUAByAG8AZgBpAGwAIABnAOkAbgDpAHIAaQBxAHUAZQAgAFIAVgBCAMEAbAB0AGEAbADhAG4AbwBzACAAUgBHAEIAIABwAHIAbwBmAGkAbJAadSgAUgBHAEKCcl9pY8+P8Md8vBgAIABSAEcAQgAg1QS4XNMMx3wARwBlAG4AZQByAGkAcwBrACAAUgBHAEIALQBwAHIAbwBmAGkAbABPAGIAZQBjAG4A/QAgAFIARwBCACAAcAByAG8AZgBpAGwF5AXoBdUF5AXZBdwAIABSAEcAQgAgBdsF3AXcBdkAUAByAG8AZgBpAGwAIABSAEcAQgAgAGcAZQBuAGUAcgBpAGMAQQBsAGwAZwBlAG0AZQBpAG4AZQBzACAAUgBHAEIALQBQAHIAbwBmAGkAbABQAHIAbwBmAGkAbABvACAAUgBHAEIAIABnAGUAbgBlAHIAaQBjAG9mbpAaAFIARwBCY8+P8GWHTvZOAIIsACAAUgBHAEIAIDDXMO0w1TChMKQw6wOTA7UDvQO5A7oDzAAgA8ADwQO/A8YDrwO7ACAAUgBHAEIAUABlAHIAZgBpAGwAIABSAEcAQgAgAGcAZQBuAOkAcgBpAGMAbwBBAGwAZwBlAG0AZQBlAG4AIABSAEcAQgAtAHAAcgBvAGYAaQBlAGwOQg4bDiMORA4fDiUOTAAgAFIARwBCACAOFw4xDkgOJw5EDhsARwBlAG4AZQBsACAAUgBHAEIAIABQAHIAbwBmAGkAbABpAFkAbABlAGkAbgBlAG4AIABSAEcAQgAtAHAAcgBvAGYAaQBpAGwAaQBHAGUAbgBlAHIAaQENAGsAaQAgAFIARwBCACAAcAByAG8AZgBpAGwAVQBuAGkAdwBlAHIAcwBhAGwAbgB5ACAAcAByAG8AZgBpAGwAIABSAEcAQgQeBDEESQQ4BDkAIAQ/BEAEPgREBDgEOwRMACAAUgBHAEIARwBlAG4AZQByAGkAYwAgAFIARwBCACAAUAByAG8AZgBpAGwAZQZFBkQGQQAgBioGOQYxBkoGQQAgAFIARwBCACAGJwZEBjkGJwZFAAB0ZXh0AAAAAENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQuAFhZWiAAAAAAAADzUgABAAAAARbPWFlaIAAAAAAAAHRNAAA97gAAA9BYWVogAAAAAAAAWnUAAKxzAAAXNFhZWiAAAAAAAAAoGgAAFZ8AALg2Y3VydgAAAAAAAAABAc0AAHNmMzIAAAAAAAEMQgAABd7///MmAAAHkgAA/ZH///ui///9owAAA9wAAMBs/8AAEQgA4QDhAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAHBwcHBwcMBwcMEQwMDBEXERERERcdFxcXFxcdIx0dHR0dHSMjIyMjIyMjKioqKioqMTExMTE3Nzc3Nzc3Nzc3P/bAEMBIiQkODQ4YDQ0YOacgJzm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5v/dAAQAD//aAAwDAQACEQMRAD8AZRRRXKZBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/0GUUUVymQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH/9FlFFFcpkFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//SZRRRXKZBRRRQAUUUUAFFFFABRRRQAUUVcittw3SU0rgVFVmOFFS/Z5j2rTCqowBS1fKVYy/s03pUbIyfeFbFBAPUUcoWMWir0tqMEx9aokEHBqGrCsFFFFIQUUUUAFFFFABRRRQAUUUUAFFFFAH/02UUUVymQUUUUAFFFFABRRRQAUUU5FLMAKALVtCCPMb8KvUABRgUVqlYsKKKKYBRRRQAVVuIQw3jqOtWqOvBoauBiUtSTIUkPp2qOsiAooopAFFFFABRRRQAUUUUAFFFFAH/1GUUUVymQUUUUAFFFFABRRRQAVYtRmX8Kr1Ytf8AW/hTW40aVFFFalBRRRQAUUUUAFFFFAFC8GGWqlXLz7y/SqdZy3JYUUUVIgooooAKKKKACiiigAooooA//9VlFFFcpkFFFFABRRRQAUUUUAFSRPscGo6KYG1RVa2k3ptPUVZrVMsKKKKACiiigApaSoppBGnuaAKNw++THpUFGSeTRWTICiiikAUUUUAFFFFABRRRQAUUUUAf/9ZlFFFcpkFFFFABRRRQAUUUUAFFFFACqxU7lrSinWQc8Gsykqk7DTNuisxLiRepyKm+2f7NVzIdy7RVL7YP7tRPcyN93inzILl2SZIxnOTWY7tI25qb1OTRUN3E2FFFFSIKKKKACiiigAooooAKKKKACiiigD//12UUUVymQUUUUAFFFFABRRRQAUUUUAFFJSgE9KACinbH9DR5cn900wG0U7y5P7po2P8A3TQA2iggjrxSUgFooooAKKKKACiiigAooooAKKKKACiiigD/0GUUUVymQUUUUAFFFFABRTkRnOFFX47ZV5bk00rjsUFR3+6M1ZW0Y/eOKvgAdBRVqI7FdbaNRg81KI416Cn0VVhhwKWkooAXNJRRQA0ojdRmomt42HAxU9FFgKLWhA+U5qs8Tp94Vr0EA9RmpcRWMWitKS2R+RwaoyRPGcGpasKxHRRRUiCiiigAooooAKKKKAP/0WUUUVymQUUUUAFSwxGVvaou+K1okEaAVUVcaQ5UVBhadRRWhQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUhAYYbpS0UAZs8JjOR0NV62HUOpU96yGG1ivpWclYloSiiipEFFFFABRRRQB//0mUUUVymQUUUUAA6j61tdqxR1H1ra7VcCkFFFFWMKKKKACiiigAooooAKKKKACiiigAooooAKKKKAFFY8v8ArG+tbArHl/1jfWpkJjKKKKzJCiiigAooooA//9NlFFFcpkFFFFAAOo+tbXasUdR9a2u1XApBRRRVjCiiigAooooAKKKKACiiigAooooAKKKKACiiigBRWPL/AKxvrWwKx5f9Y31qZCYyiiisyQooooAKKKKAP//UZRRRXKZBRRRQADqPrW12rFHUfWtrtVwKQUUUVYwooooAKKKKACiiigAooooAKKKKACiiigAooooAUVjy/wCsb61sCseX/WN9amQmMooorMkKKKKACiiigD//1WUUUVymQUUUUAA6j61tdqxR1H1ra7VcCkFFFFWMKKKKACiiigAooooAKKKKACiiigAooooAKKKKAFFY8v8ArG+tbArHl/1jfWpkJjKKKKzJCiiigAooooA//9k=",
      description: "This is a random user.",
    };
    await laLogica.modificarDatosUsuario(user);
    //console.log(res[0]);
    var res = await laLogica.obtenerDatosUsuario(1);
    assert.equal(res[0].id, 1, "¿el id es igual a 1");
    assert.equal(
      res[0].username,
      "user_3489",
      "¿el usuario no es igual a user_3489"
    );
    assert.equal(res[0].age, 27, "¿la edad no es 27?");
  }); // it
  // ....................................................
  // ....................................................
  it("puedo re-modificar los datos del usuario", async function () {
    const user = {
      id: 1,
      username: "user1",
      age: 25,
      photo:
        "/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAAqACAAQAAAABAAAA4aADAAQAAAABAAAA4QAAAAD/7QA4UGhvdG9zaG9wIDMuMAA4QklNBAQAAAAAAAA4QklNBCUAAAAAABDUHYzZjwCyBOmACZjs+EJ+/+IH2ElDQ19QUk9GSUxFAAEBAAAHyGFwcGwCIAAAbW50clJHQiBYWVogB9kAAgAZAAsAGgALYWNzcEFQUEwAAAAAYXBwbAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAABvZHNjbQAAAXgAAAWKY3BydAAABwQAAAA4d3RwdAAABzwAAAAUclhZWgAAB1AAAAAUZ1hZWgAAB2QAAAAUYlhZWgAAB3gAAAAUclRSQwAAB4wAAAAOY2hhZAAAB5wAAAAsYlRSQwAAB4wAAAAOZ1RSQwAAB4wAAAAOZGVzYwAAAAAAAAAUR2VuZXJpYyBSR0IgUHJvZmlsZQAAAAAAAAAAAAAAFEdlbmVyaWMgUkdCIFByb2ZpbGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1sdWMAAAAAAAAAHwAAAAxza1NLAAAAKAAAAYRkYURLAAAAJAAAAaxjYUVTAAAAJAAAAdB2aVZOAAAAJAAAAfRwdEJSAAAAJgAAAhh1a1VBAAAAKgAAAj5mckZVAAAAKAAAAmhodUhVAAAAKAAAApB6aFRXAAAAEgAAArhrb0tSAAAAFgAAAspuYk5PAAAAJgAAAuBjc0NaAAAAIgAAAwZoZUlMAAAAHgAAAyhyb1JPAAAAJAAAA0ZkZURFAAAALAAAA2ppdElUAAAAKAAAA5ZzdlNFAAAAJgAAAuB6aENOAAAAEgAAA75qYUpQAAAAGgAAA9BlbEdSAAAAIgAAA+pwdFBPAAAAJgAABAxubE5MAAAAKAAABDJlc0VTAAAAJgAABAx0aFRIAAAAJAAABFp0clRSAAAAIgAABH5maUZJAAAAKAAABKBockhSAAAAKAAABMhwbFBMAAAALAAABPBydVJVAAAAIgAABRxlblVTAAAAJgAABT5hckVHAAAAJgAABWQAVgFhAGUAbwBiAGUAYwBuAP0AIABSAEcAQgAgAHAAcgBvAGYAaQBsAEcAZQBuAGUAcgBlAGwAIABSAEcAQgAtAHAAcgBvAGYAaQBsAFAAZQByAGYAaQBsACAAUgBHAEIAIABnAGUAbgDoAHIAaQBjAEMepQB1ACAAaADsAG4AaAAgAFIARwBCACAAQwBoAHUAbgBnAFAAZQByAGYAaQBsACAAUgBHAEIAIABHAGUAbgDpAHIAaQBjAG8EFwQwBDMEMAQ7BEwEPQQ4BDkAIAQ/BEAEPgREBDAEOQQ7ACAAUgBHAEIAUAByAG8AZgBpAGwAIABnAOkAbgDpAHIAaQBxAHUAZQAgAFIAVgBCAMEAbAB0AGEAbADhAG4AbwBzACAAUgBHAEIAIABwAHIAbwBmAGkAbJAadSgAUgBHAEKCcl9pY8+P8Md8vBgAIABSAEcAQgAg1QS4XNMMx3wARwBlAG4AZQByAGkAcwBrACAAUgBHAEIALQBwAHIAbwBmAGkAbABPAGIAZQBjAG4A/QAgAFIARwBCACAAcAByAG8AZgBpAGwF5AXoBdUF5AXZBdwAIABSAEcAQgAgBdsF3AXcBdkAUAByAG8AZgBpAGwAIABSAEcAQgAgAGcAZQBuAGUAcgBpAGMAQQBsAGwAZwBlAG0AZQBpAG4AZQBzACAAUgBHAEIALQBQAHIAbwBmAGkAbABQAHIAbwBmAGkAbABvACAAUgBHAEIAIABnAGUAbgBlAHIAaQBjAG9mbpAaAFIARwBCY8+P8GWHTvZOAIIsACAAUgBHAEIAIDDXMO0w1TChMKQw6wOTA7UDvQO5A7oDzAAgA8ADwQO/A8YDrwO7ACAAUgBHAEIAUABlAHIAZgBpAGwAIABSAEcAQgAgAGcAZQBuAOkAcgBpAGMAbwBBAGwAZwBlAG0AZQBlAG4AIABSAEcAQgAtAHAAcgBvAGYAaQBlAGwOQg4bDiMORA4fDiUOTAAgAFIARwBCACAOFw4xDkgOJw5EDhsARwBlAG4AZQBsACAAUgBHAEIAIABQAHIAbwBmAGkAbABpAFkAbABlAGkAbgBlAG4AIABSAEcAQgAtAHAAcgBvAGYAaQBpAGwAaQBHAGUAbgBlAHIAaQENAGsAaQAgAFIARwBCACAAcAByAG8AZgBpAGwAVQBuAGkAdwBlAHIAcwBhAGwAbgB5ACAAcAByAG8AZgBpAGwAIABSAEcAQgQeBDEESQQ4BDkAIAQ/BEAEPgREBDgEOwRMACAAUgBHAEIARwBlAG4AZQByAGkAYwAgAFIARwBCACAAUAByAG8AZgBpAGwAZQZFBkQGQQAgBioGOQYxBkoGQQAgAFIARwBCACAGJwZEBjkGJwZFAAB0ZXh0AAAAAENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQuAFhZWiAAAAAAAADzUgABAAAAARbPWFlaIAAAAAAAAHRNAAA97gAAA9BYWVogAAAAAAAAWnUAAKxzAAAXNFhZWiAAAAAAAAAoGgAAFZ8AALg2Y3VydgAAAAAAAAABAc0AAHNmMzIAAAAAAAEMQgAABd7///MmAAAHkgAA/ZH///ui///9owAAA9wAAMBs/8AAEQgA4QDhAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/bAEMAHBwcHBwcMBwcMEQwMDBEXERERERcdFxcXFxcdIx0dHR0dHSMjIyMjIyMjKioqKioqMTExMTE3Nzc3Nzc3Nzc3P/bAEMBIiQkODQ4YDQ0YOacgJzm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5v/dAAQAD//aAAwDAQACEQMRAD8AZRRRXKZBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/0GUUUVymQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH/9FlFFFcpkFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//SZRRRXKZBRRRQAUUUUAFFFFABRRRQAUUVcittw3SU0rgVFVmOFFS/Z5j2rTCqowBS1fKVYy/s03pUbIyfeFbFBAPUUcoWMWir0tqMEx9aokEHBqGrCsFFFFIQUUUUAFFFFABRRRQAUUUUAFFFFAH/02UUUVymQUUUUAFFFFABRRRQAUUU5FLMAKALVtCCPMb8KvUABRgUVqlYsKKKKYBRRRQAVVuIQw3jqOtWqOvBoauBiUtSTIUkPp2qOsiAooopAFFFFABRRRQAUUUUAFFFFAH/1GUUUVymQUUUUAFFFFABRRRQAVYtRmX8Kr1Ytf8AW/hTW40aVFFFalBRRRQAUUUUAFFFFAFC8GGWqlXLz7y/SqdZy3JYUUUVIgooooAKKKKACiiigAooooA//9VlFFFcpkFFFFABRRRQAUUUUAFSRPscGo6KYG1RVa2k3ptPUVZrVMsKKKKACiiigApaSoppBGnuaAKNw++THpUFGSeTRWTICiiikAUUUUAFFFFABRRRQAUUUUAf/9ZlFFFcpkFFFFABRRRQAUUUUAFFFFACqxU7lrSinWQc8Gsykqk7DTNuisxLiRepyKm+2f7NVzIdy7RVL7YP7tRPcyN93inzILl2SZIxnOTWY7tI25qb1OTRUN3E2FFFFSIKKKKACiiigAooooAKKKKACiiigD//12UUUVymQUUUUAFFFFABRRRQAUUUUAFFJSgE9KACinbH9DR5cn900wG0U7y5P7po2P8A3TQA2iggjrxSUgFooooAKKKKACiiigAooooAKKKKACiiigD/0GUUUVymQUUUUAFFFFABRTkRnOFFX47ZV5bk00rjsUFR3+6M1ZW0Y/eOKvgAdBRVqI7FdbaNRg81KI416Cn0VVhhwKWkooAXNJRRQA0ojdRmomt42HAxU9FFgKLWhA+U5qs8Tp94Vr0EA9RmpcRWMWitKS2R+RwaoyRPGcGpasKxHRRRUiCiiigAooooAKKKKAP/0WUUUVymQUUUUAFSwxGVvaou+K1okEaAVUVcaQ5UVBhadRRWhQUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUhAYYbpS0UAZs8JjOR0NV62HUOpU96yGG1ivpWclYloSiiipEFFFFABRRRQB//0mUUUVymQUUUUAA6j61tdqxR1H1ra7VcCkFFFFWMKKKKACiiigAooooAKKKKACiiigAooooAKKKKAFFY8v8ArG+tbArHl/1jfWpkJjKKKKzJCiiigAooooA//9NlFFFcpkFFFFAAOo+tbXasUdR9a2u1XApBRRRVjCiiigAooooAKKKKACiiigAooooAKKKKACiiigBRWPL/AKxvrWwKx5f9Y31qZCYyiiisyQooooAKKKKAP//UZRRRXKZBRRRQADqPrW12rFHUfWtrtVwKQUUUVYwooooAKKKKACiiigAooooAKKKKACiiigAooooAUVjy/wCsb61sCseX/WN9amQmMooorMkKKKKACiiigD//1WUUUVymQUUUUAA6j61tdqxR1H1ra7VcCkFFFFWMKKKKACiiigAooooAKKKKACiiigAooooAKKKKAFFY8v8ArG+tbArHl/1jfWpkJjKKKKzJCiiigAooooA//9k=",
      description: "User 1 description",
    };
    await laLogica.modificarDatosUsuario(user);

    var res = await laLogica.obtenerDatosUsuario(1);
    //console.log(res[0]);

    assert.equal(res[0].id, 1, "¿el id es igual a 1");
    assert.equal(res[0].username, "user1", "¿el id es igual a 1");
    assert.equal(res[0].age, 25, "¿el id es igual a 1");
  }); // it

  it("cerrar conexión a la base de datos", async function () {
    try {
      await laLogica.cerrar();
    } catch (err) {
      // assert.equal( 0, 1, "cerrar conexión a BD fallada: " + err)
      throw new Error("cerrar conexión a BD fallada: " + err);
    }
  }); // it
}); // describe
